//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sdl.Community.SignoffVerifySettings.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageFile
    {
        public int LanguageFileId { get; set; }
        public System.Guid ProjectId { get; set; }
        public string LanguageFileGuid { get; set; }
        public string SettingsBundleGuid { get; set; }
        public string LanguageCode { get; set; }
        public string FileName { get; set; }
        public string RunAt { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
