//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sdl.Community.SignoffVerifySettings.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumberVerifierSetting
    {
        public int NumberVerifierSettingsId { get; set; }
        public System.Guid ProjectId { get; set; }
        public string FileName { get; set; }
        public string ExecutedDateTime { get; set; }
        public string TargetLanguageCode { get; set; }
        public string ApplicationVersion { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
