//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sdl.Community.SignoffVerifySettings.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.LanguageFiles = new HashSet<LanguageFile>();
            this.NumberVerifierSettings = new HashSet<NumberVerifierSetting>();
            this.QAVerificationSettings = new HashSet<QAVerificationSetting>();
            this.TargetLanguages = new HashSet<TargetLanguage>();
            this.Termbases = new HashSet<Termbase>();
            this.TranslationMemories = new HashSet<TranslationMemory>();
        }
    
        public System.Guid ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string StudioVersion { get; set; }
        public string RunAt { get; set; }
        public string SourceLanguage { get; set; }
        public string CheckRegExRules { get; set; }
        public string QACheckerRanResult { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LanguageFile> LanguageFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NumberVerifierSetting> NumberVerifierSettings { get; set; }
        public virtual Phase Phase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QAVerificationSetting> QAVerificationSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TargetLanguage> TargetLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Termbase> Termbases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TranslationMemory> TranslationMemories { get; set; }
    }
}
