//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sdl.Community.SignoffVerifySettings.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SignoffVerifySettingsEntities : DbContext
    {
        public SignoffVerifySettingsEntities()
            : base("name=SignoffVerifySettingsEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LanguageFile> LanguageFiles { get; set; }
        public virtual DbSet<NumberVerifierSetting> NumberVerifierSettings { get; set; }
        public virtual DbSet<Phase> Phases { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<QAVerificationSetting> QAVerificationSettings { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TargetLanguage> TargetLanguages { get; set; }
        public virtual DbSet<TranslationMemory> TranslationMemories { get; set; }
        public virtual DbSet<Termbase> Termbases { get; set; }
    }
}
